### ISSUE TITLE
add kornia maintainers and align with pypi version

### ISSUE THREAD

**Issue by edgarriba** [conda-forge/kornia-feedstock#11]
hi @ndmaxar @oblute @rluria14

Thanks for helping us to keep alive the project :)

Could you add us as maintainers of this repo @edgarriba @ducha-aiki @shijianjian ?

Do you guys know whether we could align this package version with the pypi ?
We just released v0.5 https://pypi.org/project/kornia/0.5.0/

Thanks !!

**Comment by mukhery** [comment]
@edgarriba are you still interested in being a maintainer on this? I can also add you to https://github.com/conda-forge/kornia-rs-feedstock

**Comment by mukhery** [comment]
@edgarriba you've been added in #46 and also to the kornia-rs-feedstock with https://github.com/conda-forge/kornia-rs-feedstock/pull/7

closing this issue

**Comment by edgarriba** [comment]
@mukhery thanks!

**Comment by mukhery** [comment]
@edgarriba good question, there's some documentation here https://conda-forge.org/docs/maintainer/ but I didn't see a nice concise explanation of what happens under the hood... Hopefully, we don't need to do anything. Since merging https://github.com/conda-forge/kornia-feedstock/pull/43, the CI system should automatically detect changes, create a PR, and then assuming all the builds complete without any errors it should automatically merge the PR. [This recipe monitors pypi](https://github.com/conda-forge/kornia-feedstock/blob/1261bd99697a7eb9f78b2351ac65211f69cacdb3/recipe/meta.yaml#L8-L10) for updates, so several hours after you release a new version there, this feedstock should automatically update.

**Comment by edgarriba** [comment]
@mukhery perfect, we'll see soon next week after the 0.7.3 release :)
